@BASE_URL=http://localhost:3000

### Register Doctor
POST {{BASE_URL}}/auth/register/doctor
Content-Type: application/json

{
 "username":"doctor",
 "password":"123456",
 "specialization":"Cardiologist"
}

### Register User
POST {{BASE_URL}}/auth/register/user
Content-Type: application/json

{
 "username":"user1",
 "password":"123456"
}

### Login Doctor
POST {{BASE_URL}}/auth/login/doctor
Content-Type: application/json

{
 "username":"doctor1",
 "password":"123456"
}

### Login User
POST {{BASE_URL}}/auth/login/user
Content-Type: application/json

{
 "username":"user1",
 "password":"123456"
}